### ISSUE TITLE
token bot

### ISSUE THREAD

**Issue by Fedelhoo** [gabriel-preti-ferraz/Bot-Raid#1]
onde eu poderia colocar o token do bot no projeto do raid do discord ?

**Comment by gabriel-preti-ferraz** [comment]
# Bot RAID

### Olá Fedelhoo!

Você pode colocar o <strong>token</strong> do seu bot na última linha da <strong>index.js</strong>, tudo que você precisa para conseguir fazer o bot funcionar está no README.md

>  Até mais!
