### ISSUE TITLE
.ban all error

### ISSUE THREAD

**Issue by Fedelhoo** [gabriel-preti-ferraz/Bot-Raid#2]
O comando .banall apresenta erro e quando inserido o bot fecha imediatamente. agradeco caso possa resolver

**Comment by gabriel-preti-ferraz** [comment]
Bom dia!
Consegue me enviar o erro?

**Comment by gabriel-preti-ferraz** [comment]
<h2 align='center'>
   Issue fechada por falta de informações
</h2>
